/**
 * Grunt project config file
 *
 * -----------------------------------------------------------------------------
 * @see http://gruntjs.com/getting-started
 * @see http://www.chapterthree.com/blog/rob-decker/theme-development-grunt-livereload-lint-uglify-oh-my
 * -----------------------------------------------------------------------------
 * @see https://github.com/gruntjs/grunt-contrib-uglify
 * -----------------------------------------------------------------------------
 *
 * Интсрукция по использованию:
 * 1) Перейти в корень проекта (где находится файл Gruntfile.js)
 * 2) Самый первый раз (если еще не выволнялясь установка nodejs модулей
 *    необходимых для проекта) выполнить команду:
 *
 *      nmp install
 *
 * 3) Для выполнения задачи конкатинации и минификации файлов проекта, выполнить команду:
 *
 *      grunt
 *
 * 3.1) Чтобы выполнить только конкатинацию js файлов:
 *
 *      grunt concat
 *
 * 3.2) Чтобы выполнить только минификацию js файлов:
 *
 *      grunt uglify
 *
 * 3.3) Чтобы выполнить только минификацию css файлов
 *      grunt cssmin
 *
 * @param grunt object
 * @returns void
 */
module.exports = function(grunt) {
    // Project configuration
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        // ------------------------- CONCATINATION -----------------------------
        // @see https://github.com/gruntjs/grunt-contrib-concat
        concat: {
            options: {
                separator: ';'
            },
            dist: {
                src: [
                    'public/js/jquery-1.9.1.js',
                    'public/js/jquery.cookie.js',
                    'public/js/modernizr.js',
                ],
                dest: 'public/js/head-scripts.js'
            }
        },

        // --------------------- JS MINIFIER (UGLIFY) --------------------------
        // @see https://github.com/gruntjs/grunt-contrib-uglify
        uglify: {
            options: {
                banner: '/*! Generated by gruntjs uglify on <%= grunt.template.today("yyyy-mm-dd") %> */\n',
                compress: true,
                preserveComments: false,
                beautify: false,
                mangle: false           // вкл./выкл. замены имен переменных на короткие названия
            },
            my_target: {
                files: {
                    'public/js/head-scripts.min.js': 'public/js/head-scripts.js',
                    // other js files goes here...
                }
            }
        },

        // ------------------------- CSS MINIFIER ------------------------------
        // @see https://github.com/gruntjs/grunt-contrib-cssmin
        cssmin: {
            combine: {
                files: {
                    'public/css/styles.min.css': ['public/css/normalize.css',
                                                  'public/css/basemod-classes.css',
                                                  'public/css/main-style.css',
                                                  'public/css/frontend-main-style.css']
                }
            }
        }
    });

    // ------------------------------ TASKS ------------------------------------
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.registerTask('default', ['concat', 'uglify', 'cssmin']);
};
